# @package _group_
# https://pytorch-lightning.readthedocs.io/en/stable/trainer.html#trainer-flags
_target_: pytorch_lightning.Trainer
params:
  max_epochs: 100
  gpus: 1
  precision: 16
  terminate_on_nan: true

  #limit_train_batches: 32
  limit_val_batches: 6
  
  # Update this to specify output filepath for logs / tensorboard
  default_root_dir: /mnt/iscsi/fcos

  # Uncomment to print all model weights
  #weights_summary: full
  
  logger:
    _target_: pytorch_lightning.loggers.TensorBoardLogger
    params:
      save_dir: ${trainer.params.default_root_dir}
      name: ${now:%Y-%m-%d}
      version: ${now:%H-%M-%S}
              

  callbacks:

    - _target_: combustion.lightning.callbacks.BlendVisualizeCallback
      params: 
        name: 'pred/types'
        triggers: ['train']
        attr_name: "last_cls"
        interval: 500
        colormap: [null, "gnuplot"]
        alpha: [1.0, 0.8]

    - _target_: combustion.lightning.callbacks.BlendVisualizeCallback
      params: 
        name: 'pred/centerness'
        triggers: ['train']
        attr_name: "last_centerness"
        interval: 500
        colormap: [null, "gnuplot"]
        alpha: [1.0, 0.8]

    - _target_: combustion.lightning.callbacks.KeypointVisualizeCallback
      params: 
        name: 'true/boxes'
        triggers: ['train']
        attr_name: "last_target"
        interval: 500

    - _target_: combustion.lightning.callbacks.BlendVisualizeCallback
      params: 
        name: 'pred/types'
        triggers: ['val', 'test']
        attr_name: "last_cls"
        colormap: [null, "gnuplot"]
        alpha: [1.0, 0.8]
        epoch_counter: True
        max_calls: 32
        split_batches: True

    - _target_: combustion.lightning.callbacks.BlendVisualizeCallback
      params: 
        name: 'pred/centerness'
        triggers: ['val', 'test']
        attr_name: "last_centerness"
        colormap: [null, "gnuplot"]
        alpha: [1.0, 0.8]
        epoch_counter: True
        max_calls: 32
        split_batches: True

    - _target_: combustion.lightning.callbacks.KeypointVisualizeCallback
      params: 
        name: 'pred/boxes'
        triggers: ['val', 'test']
        attr_name: "last_pred"
        epoch_counter: True
        max_calls: 32
        split_batches: True

    - _target_: combustion.lightning.callbacks.KeypointVisualizeCallback
      params: 
        name: 'true/boxes'
        triggers: ['val', 'test']
        attr_name: "last_target"
        epoch_counter: True
        max_calls: 32
        split_batches: True
